### ISSUE TITLE
Сторінка додавання звіту про рибалку користувачами

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#12]
- [x] Зробити форму додавання звіту.
це має бути просте поле з форматованим текстом (**в який можна вставляти з буферу обміну форматовний текст** - це потрібно для того, щоб я пізніше переніс всі звіти з нашого форуму), пропоную користуватись вже існуючим редактором. [P1]
- [x] Прив'язати звіт до конкретної водойми. https://github.com/rivnefish/rivnefish/issues/25 [P2]
- [x] рейтинг задоволення рибалкою в зірочках. 
Суміжнє іш'ю: https://github.com/rivnefish/rivnefish/issues/9 [P3]
- [x] дата і час рибалки [P3]
- [x] тип рибалки: поплавок, фідер, карпфішинг, спіннінг, спутнік, зимна рибалка, літня мормишка https://github.com/rivnefish/rivnefish/issues/23 [P3]
- [x] риба, яку було спіймано: кількість штук і загальна вага - саме за допомогою цих даних ми будемо формувати показник кльову конкретних риб на конкретних водоймах. [P3]
- [x] окремо виділити трофей рибалки і його вагу [P3]
- [x] на яку наживку клювала риба? це може бути критично корисно для інших рибалок.  https://github.com/rivnefish/rivnefish/issues/24 [P3]
- [x] фотографії з рибалки [P4]
- ~~**айтем до обговорення:** якщо водойми на мапі немає - додавати її в базу. Назву брати з Google Maps API найближчого населеного пункту~~
- ~~**айтем до обговорення:** дозволити додавати звіти на "приватну водойму" - у випадках, коли користувач не хоче світити місце, не він ловив рибу, але дуже хоча написати звіт і похвастатись уловом і своїм вмінням. Саме так пишуть звіти такі відомі(в певних колах) рибалки як Салапін і Ромео.~~
- [x] Додати кнопку "Написати звіт" на головну сторінку. (може краще відразу на мапу?)
- [x] Додати кнопку "Написати звіт" на бокову панель, щоб її було видно завжди і всюди.
- [x] Інформування листом про доданий звіт: адміністраторів сайту і також автора звіту. Текст обговоримо окремо.
- ~~Додати в профайл користувача кількість доданих ним звітів і посилання на них.~~ (додасться після створення профайлу, винести в окремий таск)

**Звіту** про рибалку (надалі "звіт") - це невід'ємна складова нашого ресурсу. Людина, яка поїхала на рибалку і повернулась додому неодмінно хоче:

1. Поділитись своєю радістю зі всім світом.
2. Записати всі умови, при яких відбулась дуже вдала (чи зовсім навпаки) рибалка. Щоб наступний раз мати можливість проаналізувати ці дані і зробити те ж саме.
3. Показати фоточки з місця подій.
4. Записати рекорд по розмір риби цієї водойми (або свій особистий).
5. Отримати фідбек від таких же користувачів-рибалок.

Зі своєї сторони нам для задоволення всіх цих потреб користувачів потрібно:
(Постійно тримати в голові, що ми маємо зробити цю фічу такою, що можна буде її реалізувати і на мобільних додатках)

Мокап:
![image](https://cloud.githubusercontent.com/assets/5851581/13666589/ee65e7c2-e6ba-11e5-82f1-4049c0e67f3d.png)

**Comment by ttp** [comment]
@MasterSergius я посидів подумав, що мабуть треба поточні описи місць винести в універсальну штуку **articles** із поліморфним зв"язком на місця і нові звіти, детальніше отут http://guides.rubyonrails.org/association_basics.html#polymorphic-associations

**Comment by stal1n274** [comment]
Сергій, який хоча б орієнтовний термін реалізації цієї штуки? тижднь-місяць-три?

**Comment by ttp** [comment]
@stal1n274  значить так, я б на це все дав десь 3 неділі повної зайнятості(а то й більше) і це десь 120год. Враховуючи, що Сергій має часу ну десь 2Год в тиждень, то воно буде робитись ~60 тижнів, отака математика.
@MasterSergius я б почав з схеми для БД і міграції для неї, це найперше, що треба зробити.

**Comment by MasterSergius** [comment]
Цілком згідний з обома, і, було би добре хоча б 1 годинку в тиждень посидіти разом, так може кінцевий термін трохи зменшиться, бо швидше розберусь з цим всім

**Comment by ttp** [comment]
60 тижнів пройшло :smile_cat: , переглянь

**Comment by stal1n274** [comment]
Дуже дякую, що все так швидко зробили і з усім впорались!

Кілька зауважень:
1. Не можна вибрати час рибалки
2. бляха муха, а більше зауважень і нема!

**Comment by stal1n274** [comment]
Все працює.
