### ISSUE TITLE
Рейтинг дописів(звітів з рибалок)

### ISSUE THREAD

**Issue by stal1n274** [rivnefish/rivnefish#67]
Нам потрібно мати систему, за допомогою якої користувачі будуть "лайкати" дописи інших авторів.

Пропоную зробити цю систему максимально простою, на вибір давати лише дві опції: "подобається" або "не подобається". 

На основі цих даних ми будемо проводити конкурсу, будувати статистику і виводити найбільш популярний контент.

## Todo
- [x] Проголосувати за звіт(лише один раз)
- [x] Відмінити свій голос (як позитивний так і негативний)
- [x] Змінити свій голос (з позитивного на негативний і навпаки)
- [x] Показувати голоси на сторінці звіту у вигляді 2-ох цифр: + (25)/- (5)
- [x] Показувати рейтинг на стрічці репортів. Зведену оцінку: +25-5=**20**

**Comment by stal1n274** [comment]
👍
